### PR TITLE
No empty description for polymorphic subtypes

### LINKED ISSUE #2370: Empty schema description if polymorphic subtype missing Javadoc
**Describe the bug**

- springdoc-openapi-javadoc causes an empty schema description to be generated for classes that are polymorphic subtypes and missing a Javadoc comment.

**To Reproduce**
Steps to reproduce the behavior: See linked pull request (#2371)

**Expected behavior**

- Schema description should remain null if class Javadoc is missing.

**Additional context**
Probably has the same cause as #2035 .

### PR DESCRIPTION
**Pull request by westse**
- Fixes #2370

### CODE REVIEW

File: springdoc-openapi-tests/springdoc-openapi-javadoc-tests/src/test/java/test/org/springdoc/api/app170/Cat.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
+package test.org.springdoc.api.app170;
+
+
+import io.swagger.v3.oas.annotations.media.Schema;
+
+@Schema
+public class Cat implements Animal {
```
Comment (westse) [inline springdoc-openapi-tests/springdoc-openapi-javadoc-tests/src/test/java/test/org/springdoc/api/app170/Cat.java:7]: Notice missing class Javadoc (and no explicit description set on `@Schema`), which should translate to null `Schema.description`

**Comment by bnasslahsen** [comment]
@westse, 

Thank you for your contribution to the project.
